// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhitsgkjosxynfeigpsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoaXRzZ2tqb3N4eW5mZWlncHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4ODg5NTcsImV4cCI6MjA4NTQ2NDk1N30.QqAVNN9ZUVqu36_j2NCh6a-2DJaHUpf03yDkIp0Cmss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});